# -*- coding: utf-8 -*-
"""Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-zO6aKNgE4W5CnYH3CJun9RWiiIBN1o
"""

!pip install ultralytics

# Import
from google.colab import drive
from ultralytics import YOLO

# Mount drive
drive.mount('/content/drive')

# Get model
model = YOLO("yolo11n.pt")

# Train model
model.train(
    data = '/content/drive/MyDrive/DatasetColab.yaml',
    epochs = 100,               # 속도 30 → 100 정확도
    imgsz = 640,                # 속도 416 → 640 정확도
    batch = 16,                 # 속도 32 → 16 정확도
    patience = 20,              # 조기 종료 방지
    optimizer = "SGD",          # Adam보다 일반화 잘되는 경우 많음
    cos_lr = True,              # Cosine learning rate 스케줄링
    amp = True,                 # 자동 혼합 정밀도
    workers = 2,                # Colab은 낮은 값 권장
    augment = True
)